name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build and Release Tauri App (Mac Metal)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Sumrzr ${{ github.ref_name }}'
          releaseBody: 'Se nedan för filer att ladda ner för Mac (DMG) och Windows (EXE).'
          releaseDraft: true
          prerelease: false
          args: --features metal

  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Enable Long Paths
        run: |
          git config --system core.longpaths true
          Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Force

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.3.268.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: false

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build and Release Tauri App (Windows Vulkan)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WHISPER_NO_AVX2: 1
          WHISPER_NO_FMA: 1
          WHISPER_NO_F16C: 1
          LLAMA_NO_AVX2: 1
          LLAMA_NO_FMA: 1
          LLAMA_NO_F16C: 1
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Sumrzr ${{ github.ref_name }}'
          releaseBody: 'Se nedan för filer att ladda ner för Mac (DMG) och Windows (EXE).'
          releaseDraft: true
          prerelease: false
          args: --no-default-features --features vulkan
